vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_thumbnail:
            uri_prefix: /upload/img/postThumb
            upload_destination: '%kernel.project_dir%/public/upload/img/postThumb'
            namer: App\Namer\PostThumbnailNamer
            delete_on_update: true
            delete_on_remove: true
        profile_picture_upload:
            uri_prefix: /upload/img/profilePicture
            upload_destination: '%kernel.project_dir%/public/upload/img/profilePicture'
            namer: App\Namer\PostThumbnailNamer
            delete_on_update: true
            delete_on_remove: true
        company_logo_uri:
            uri_prefix: /upload/img/logo
            upload_destination: '%kernel.project_dir%/public/upload/img/logo'
            namer: App\Namer\PostThumbnailNamer
            delete_on_update: true
            delete_on_remove: true
        invest_picture_upload:
            uri_prefix: /upload/img/invest
            upload_destination: '%kernel.project_dir%/public/upload/img/invest'
            namer: App\Namer\PostThumbnailNamer
            delete_on_update: true
            delete_on_remove: true
        seal_upload:
            uri_prefix: /upload/img/seal
            upload_destination: '%kernel.project_dir%/public/upload/img/seal'
            namer: App\Namer\PostThumbnailNamer
            delete_on_update: true
            delete_on_remove: true
        flag_upload:
            uri_prefix: /upload/img/flag
            upload_destination: '%kernel.project_dir%/public/upload/img/flag'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update: true
            delete_on_remove: true