# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    acme_api.event.jwt_created_listener:
        class: App\Events\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    acme_api.event.authentication_failure_listener:
        class: App\Events\AuthenticationFailureListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    acme_api.event.authentication_success_listener:
        class: App\Events\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    App\Namer\PostThumbnailNamer:
        public: true
        tags:
            - { name: vich_uploader.namer, mapping: post_thumbnail }
    # App\Doctrine\ProfilePictureActiveExtension:
    #     tags:
    #         - { name: api_platform.doctrine.orm.query_extension.collection }
    #         - { name: api_platform.doctrine.orm.query_extension.item }
    App\Controller\CustomImageController:
        tags: ['controller.service_arguments']
    App\Controller\PostController:
        tags: ['controller.service_arguments']
    App\Controller\UserCustomController:
        tags: ['controller.service_arguments']
    App\Filter\CompanyTypeTitleFilter:
        tags: ['api_platform.filter']
    App\Filter\CompanySizeFilter:
        tags: ['api_platform.filter']


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
